package org.laidu.bookStore.domain;

public class Book {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.Id
     *
     * @mbg.generated Mon Sep 12 23:32:28 GMT+08:00 2016
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.Title
     *
     * @mbg.generated Mon Sep 12 23:32:28 GMT+08:00 2016
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.Price
     *
     * @mbg.generated Mon Sep 12 23:32:28 GMT+08:00 2016
     */
    private Float price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.Author
     *
     * @mbg.generated Mon Sep 12 23:32:28 GMT+08:00 2016
     */
    private String author;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.Publisher
     *
     * @mbg.generated Mon Sep 12 23:32:28 GMT+08:00 2016
     */
    private String publisher;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.Amount
     *
     * @mbg.generated Mon Sep 12 23:32:28 GMT+08:00 2016
     */
    private Integer amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.faceimg
     *
     * @mbg.generated Mon Sep 12 23:32:28 GMT+08:00 2016
     */
    private String faceimg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.describe
     *
     * @mbg.generated Mon Sep 12 23:32:28 GMT+08:00 2016
     */
    private String describe;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.Id
     *
     * @return the value of book.Id
     *
     * @mbg.generated Mon Sep 12 23:32:28 GMT+08:00 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.Id
     *
     * @param id the value for book.Id
     *
     * @mbg.generated Mon Sep 12 23:32:28 GMT+08:00 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.Title
     *
     * @return the value of book.Title
     *
     * @mbg.generated Mon Sep 12 23:32:28 GMT+08:00 2016
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.Title
     *
     * @param title the value for book.Title
     *
     * @mbg.generated Mon Sep 12 23:32:28 GMT+08:00 2016
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.Price
     *
     * @return the value of book.Price
     *
     * @mbg.generated Mon Sep 12 23:32:28 GMT+08:00 2016
     */
    public Float getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.Price
     *
     * @param price the value for book.Price
     *
     * @mbg.generated Mon Sep 12 23:32:28 GMT+08:00 2016
     */
    public void setPrice(Float price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.Author
     *
     * @return the value of book.Author
     *
     * @mbg.generated Mon Sep 12 23:32:28 GMT+08:00 2016
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.Author
     *
     * @param author the value for book.Author
     *
     * @mbg.generated Mon Sep 12 23:32:28 GMT+08:00 2016
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.Publisher
     *
     * @return the value of book.Publisher
     *
     * @mbg.generated Mon Sep 12 23:32:28 GMT+08:00 2016
     */
    public String getPublisher() {
        return publisher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.Publisher
     *
     * @param publisher the value for book.Publisher
     *
     * @mbg.generated Mon Sep 12 23:32:28 GMT+08:00 2016
     */
    public void setPublisher(String publisher) {
        this.publisher = publisher == null ? null : publisher.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.Amount
     *
     * @return the value of book.Amount
     *
     * @mbg.generated Mon Sep 12 23:32:28 GMT+08:00 2016
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.Amount
     *
     * @param amount the value for book.Amount
     *
     * @mbg.generated Mon Sep 12 23:32:28 GMT+08:00 2016
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.faceimg
     *
     * @return the value of book.faceimg
     *
     * @mbg.generated Mon Sep 12 23:32:28 GMT+08:00 2016
     */
    public String getFaceimg() {
        return faceimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.faceimg
     *
     * @param faceimg the value for book.faceimg
     *
     * @mbg.generated Mon Sep 12 23:32:28 GMT+08:00 2016
     */
    public void setFaceimg(String faceimg) {
        this.faceimg = faceimg == null ? null : faceimg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.describe
     *
     * @return the value of book.describe
     *
     * @mbg.generated Mon Sep 12 23:32:28 GMT+08:00 2016
     */
    public String getDescribe() {
        return describe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.describe
     *
     * @param describe the value for book.describe
     *
     * @mbg.generated Mon Sep 12 23:32:28 GMT+08:00 2016
     */
    public void setDescribe(String describe) {
        this.describe = describe == null ? null : describe.trim();
    }
}