package org.laidu.bookStore.domain;

public class Cart {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.id
     *
     * @mbg.generated Mon Sep 12 23:32:28 GMT+08:00 2016
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.uid
     *
     * @mbg.generated Mon Sep 12 23:32:28 GMT+08:00 2016
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.bid
     *
     * @mbg.generated Mon Sep 12 23:32:28 GMT+08:00 2016
     */
    private Integer bid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.price
     *
     * @mbg.generated Mon Sep 12 23:32:28 GMT+08:00 2016
     */
    private Float price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.totalprice
     *
     * @mbg.generated Mon Sep 12 23:32:28 GMT+08:00 2016
     */
    private Float totalprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.counts
     *
     * @mbg.generated Mon Sep 12 23:32:28 GMT+08:00 2016
     */
    private Integer counts;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.id
     *
     * @return the value of cart.id
     *
     * @mbg.generated Mon Sep 12 23:32:28 GMT+08:00 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.id
     *
     * @param id the value for cart.id
     *
     * @mbg.generated Mon Sep 12 23:32:28 GMT+08:00 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.uid
     *
     * @return the value of cart.uid
     *
     * @mbg.generated Mon Sep 12 23:32:28 GMT+08:00 2016
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.uid
     *
     * @param uid the value for cart.uid
     *
     * @mbg.generated Mon Sep 12 23:32:28 GMT+08:00 2016
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.bid
     *
     * @return the value of cart.bid
     *
     * @mbg.generated Mon Sep 12 23:32:28 GMT+08:00 2016
     */
    public Integer getBid() {
        return bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.bid
     *
     * @param bid the value for cart.bid
     *
     * @mbg.generated Mon Sep 12 23:32:28 GMT+08:00 2016
     */
    public void setBid(Integer bid) {
        this.bid = bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.price
     *
     * @return the value of cart.price
     *
     * @mbg.generated Mon Sep 12 23:32:28 GMT+08:00 2016
     */
    public Float getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.price
     *
     * @param price the value for cart.price
     *
     * @mbg.generated Mon Sep 12 23:32:28 GMT+08:00 2016
     */
    public void setPrice(Float price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.totalprice
     *
     * @return the value of cart.totalprice
     *
     * @mbg.generated Mon Sep 12 23:32:28 GMT+08:00 2016
     */
    public Float getTotalprice() {
        return totalprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.totalprice
     *
     * @param totalprice the value for cart.totalprice
     *
     * @mbg.generated Mon Sep 12 23:32:28 GMT+08:00 2016
     */
    public void setTotalprice(Float totalprice) {
        this.totalprice = totalprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.counts
     *
     * @return the value of cart.counts
     *
     * @mbg.generated Mon Sep 12 23:32:28 GMT+08:00 2016
     */
    public Integer getCounts() {
        return counts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.counts
     *
     * @param counts the value for cart.counts
     *
     * @mbg.generated Mon Sep 12 23:32:28 GMT+08:00 2016
     */
    public void setCounts(Integer counts) {
        this.counts = counts;
    }
}