package org.laidu.bookStore.domain;

public class Orderdetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderdetail.Id
     *
     * @mbg.generated Mon Sep 12 23:32:28 GMT+08:00 2016
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderdetail.Oid
     *
     * @mbg.generated Mon Sep 12 23:32:28 GMT+08:00 2016
     */
    private Integer oid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderdetail.Bid
     *
     * @mbg.generated Mon Sep 12 23:32:28 GMT+08:00 2016
     */
    private Integer bid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderdetail.Counts
     *
     * @mbg.generated Mon Sep 12 23:32:28 GMT+08:00 2016
     */
    private Integer counts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderdetail.buyprice
     *
     * @mbg.generated Mon Sep 12 23:32:28 GMT+08:00 2016
     */
    private Float buyprice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderdetail.Id
     *
     * @return the value of orderdetail.Id
     *
     * @mbg.generated Mon Sep 12 23:32:28 GMT+08:00 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderdetail.Id
     *
     * @param id the value for orderdetail.Id
     *
     * @mbg.generated Mon Sep 12 23:32:28 GMT+08:00 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderdetail.Oid
     *
     * @return the value of orderdetail.Oid
     *
     * @mbg.generated Mon Sep 12 23:32:28 GMT+08:00 2016
     */
    public Integer getOid() {
        return oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderdetail.Oid
     *
     * @param oid the value for orderdetail.Oid
     *
     * @mbg.generated Mon Sep 12 23:32:28 GMT+08:00 2016
     */
    public void setOid(Integer oid) {
        this.oid = oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderdetail.Bid
     *
     * @return the value of orderdetail.Bid
     *
     * @mbg.generated Mon Sep 12 23:32:28 GMT+08:00 2016
     */
    public Integer getBid() {
        return bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderdetail.Bid
     *
     * @param bid the value for orderdetail.Bid
     *
     * @mbg.generated Mon Sep 12 23:32:28 GMT+08:00 2016
     */
    public void setBid(Integer bid) {
        this.bid = bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderdetail.Counts
     *
     * @return the value of orderdetail.Counts
     *
     * @mbg.generated Mon Sep 12 23:32:28 GMT+08:00 2016
     */
    public Integer getCounts() {
        return counts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderdetail.Counts
     *
     * @param counts the value for orderdetail.Counts
     *
     * @mbg.generated Mon Sep 12 23:32:28 GMT+08:00 2016
     */
    public void setCounts(Integer counts) {
        this.counts = counts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderdetail.buyprice
     *
     * @return the value of orderdetail.buyprice
     *
     * @mbg.generated Mon Sep 12 23:32:28 GMT+08:00 2016
     */
    public Float getBuyprice() {
        return buyprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderdetail.buyprice
     *
     * @param buyprice the value for orderdetail.buyprice
     *
     * @mbg.generated Mon Sep 12 23:32:28 GMT+08:00 2016
     */
    public void setBuyprice(Float buyprice) {
        this.buyprice = buyprice;
    }
}