package org.laidu.bookStore.domain;

import java.util.Date;

public class Order {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.Id
     *
     * @mbg.generated Mon Sep 12 23:32:28 GMT+08:00 2016
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.Uid
     *
     * @mbg.generated Mon Sep 12 23:32:28 GMT+08:00 2016
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.BuyDate
     *
     * @mbg.generated Mon Sep 12 23:32:28 GMT+08:00 2016
     */
    private Date buydate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.totalprice
     *
     * @mbg.generated Mon Sep 12 23:32:28 GMT+08:00 2016
     */
    private Float totalprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.receiver
     *
     * @mbg.generated Mon Sep 12 23:32:28 GMT+08:00 2016
     */
    private String receiver;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.rphone
     *
     * @mbg.generated Mon Sep 12 23:32:28 GMT+08:00 2016
     */
    private String rphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.raddress
     *
     * @mbg.generated Mon Sep 12 23:32:28 GMT+08:00 2016
     */
    private String raddress;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.Id
     *
     * @return the value of orders.Id
     *
     * @mbg.generated Mon Sep 12 23:32:28 GMT+08:00 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.Id
     *
     * @param id the value for orders.Id
     *
     * @mbg.generated Mon Sep 12 23:32:28 GMT+08:00 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.Uid
     *
     * @return the value of orders.Uid
     *
     * @mbg.generated Mon Sep 12 23:32:28 GMT+08:00 2016
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.Uid
     *
     * @param uid the value for orders.Uid
     *
     * @mbg.generated Mon Sep 12 23:32:28 GMT+08:00 2016
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.BuyDate
     *
     * @return the value of orders.BuyDate
     *
     * @mbg.generated Mon Sep 12 23:32:28 GMT+08:00 2016
     */
    public Date getBuydate() {
        return buydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.BuyDate
     *
     * @param buydate the value for orders.BuyDate
     *
     * @mbg.generated Mon Sep 12 23:32:28 GMT+08:00 2016
     */
    public void setBuydate(Date buydate) {
        this.buydate = buydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.totalprice
     *
     * @return the value of orders.totalprice
     *
     * @mbg.generated Mon Sep 12 23:32:28 GMT+08:00 2016
     */
    public Float getTotalprice() {
        return totalprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.totalprice
     *
     * @param totalprice the value for orders.totalprice
     *
     * @mbg.generated Mon Sep 12 23:32:28 GMT+08:00 2016
     */
    public void setTotalprice(Float totalprice) {
        this.totalprice = totalprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.receiver
     *
     * @return the value of orders.receiver
     *
     * @mbg.generated Mon Sep 12 23:32:28 GMT+08:00 2016
     */
    public String getReceiver() {
        return receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.receiver
     *
     * @param receiver the value for orders.receiver
     *
     * @mbg.generated Mon Sep 12 23:32:28 GMT+08:00 2016
     */
    public void setReceiver(String receiver) {
        this.receiver = receiver == null ? null : receiver.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.rphone
     *
     * @return the value of orders.rphone
     *
     * @mbg.generated Mon Sep 12 23:32:28 GMT+08:00 2016
     */
    public String getRphone() {
        return rphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.rphone
     *
     * @param rphone the value for orders.rphone
     *
     * @mbg.generated Mon Sep 12 23:32:28 GMT+08:00 2016
     */
    public void setRphone(String rphone) {
        this.rphone = rphone == null ? null : rphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.raddress
     *
     * @return the value of orders.raddress
     *
     * @mbg.generated Mon Sep 12 23:32:28 GMT+08:00 2016
     */
    public String getRaddress() {
        return raddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.raddress
     *
     * @param raddress the value for orders.raddress
     *
     * @mbg.generated Mon Sep 12 23:32:28 GMT+08:00 2016
     */
    public void setRaddress(String raddress) {
        this.raddress = raddress == null ? null : raddress.trim();
    }
}