package org.laidu.bookStore.mapper;

import org.laidu.bookStore.domain.Book;
import org.laidu.bookStore.model.BookModel;

import java.util.List;

public interface BookMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated Mon Sep 12 23:32:28 GMT+08:00 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated Mon Sep 12 23:32:28 GMT+08:00 2016
     */
    int insert(Book record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated Mon Sep 12 23:32:28 GMT+08:00 2016
     */
    int insertSelective(Book record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated Mon Sep 12 23:32:28 GMT+08:00 2016
     */
    Book selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated Mon Sep 12 23:32:28 GMT+08:00 2016
     */
    int updateByPrimaryKeySelective(Book record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated Mon Sep 12 23:32:28 GMT+08:00 2016
     */
    int updateByPrimaryKey(Book record);

    List<BookModel> findList();

}