package org.laidu.bookStore.mapper;

import org.laidu.bookStore.domain.Orderdetail;
import org.laidu.bookStore.model.OrderdetailModel;

import java.util.List;

public interface OrderdetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetail
     *
     * @mbg.generated Mon Sep 12 23:32:28 GMT+08:00 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetail
     *
     * @mbg.generated Mon Sep 12 23:32:28 GMT+08:00 2016
     */
    int insert(Orderdetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetail
     *
     * @mbg.generated Mon Sep 12 23:32:28 GMT+08:00 2016
     */
    int insertSelective(Orderdetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetail
     *
     * @mbg.generated Mon Sep 12 23:32:28 GMT+08:00 2016
     */
    Orderdetail selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetail
     *
     * @mbg.generated Mon Sep 12 23:32:28 GMT+08:00 2016
     */
    int updateByPrimaryKeySelective(Orderdetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderdetail
     *
     * @mbg.generated Mon Sep 12 23:32:28 GMT+08:00 2016
     */
    int updateByPrimaryKey(Orderdetail record);

    List<OrderdetailModel> findDetailByOid(int oid);
}